"""
Florida DBPR Food Service Violation Code Lookup (effective post 1/1/2013)
Source: https://www2.myfloridalicense.com/hotels-restaurants/public-records/
Violations numbered 1-58, corresponding to CSV columns "Violation 01".."Violation 58"
"""

VIOLATION_CODES = {
    1: "Approved source",
    2: "Original container: labeling, date marking, consumer advisory",
    3: "Time/Temperature Control for Safety (TCS) food out of temperature",
    4: "Facilities to maintain proper food temperature",
    5: "Food/equipment thermometers provided and accurate",
    6: "TCS foods properly thawed",
    7: "Unwrapped or TCS food not re-served",
    8: "Food protection / cross-contamination",
    9: "Bare hand contact with ready-to-eat food",
    10: "In-use food dispensing utensils properly stored",
    11: "Employee health knowledge; ill/symptomatic employee present",
    12: "Hands washed, good hygienic practices",
    13: "Clean clothes; hair restraints; jewelry",
    14: "Food/non-food contact surfaces designed/maintained",
    15: "(not used)",
    16: "Dishwashing facilities; chemical test kits; gauges",
    17: "(not used)",
    18: "(not used)",
    19: "(not used)",
    20: "(not used)",
    21: "Wiping cloths; clean/soiled linens; laundry facilities",
    22: "Food-contact surfaces clean and sanitized",
    23: "Non-food contact surfaces clean",
    24: "Storage/handling of clean equipment, utensils; air drying",
    25: "Single-service and single-use items",
    26: "(not used)",
    27: "Water source safe, hot and cold under pressure",
    28: "Sewage and wastewater disposed properly",
    29: "Plumbing installed and maintained; backflow prevention",
    30: "(not used)",
    31: "Hand wash sinks, supplies, and signage",
    32: "Bathrooms",
    33: "Garbage and refuse; premises maintained",
    34: "(not used)",
    35: "Presence/breeding of insects, rodents, pests",
    36: "Floors, walls, ceilings; rooms/equipment vented",
    37: "(not used)",
    38: "Lighting provided as required",
    39: "(not used)",
    40: "Employee personal belongings",
    41: "Chemicals/toxic substances",
    42: "Cleaning and maintenance equipment",
    43: "Complete separation from living/sleeping area; kitchen restricted",
    44: "(not used)",
    45: "Fire extinguishing equipment (reporting only)",
    46: "Exits not blocked or locked (reporting only)",
    47: "Electrical wiring/outlets in good repair (reporting only)",
    48: "Gas appliances; boiler certificate (reporting only)",
    49: "Flammable/combustible materials (reporting only)",
    50: "Current license properly displayed",
    51: "Other conditions sanitary and safe operation",
    52: "Misrepresentation; misbranding",
    53: "Food management certification / employee training verification",
    54: "Florida Clean Indoor Air Act",
    55: "Automatic Gratuity Notice",
    56: "(not used)",
    57: "(not used)",
    58: "(not used)",
}

# Violations widely considered "high risk" / food-safety critical (rough heuristic
# based on FDA risk-factor categories: temperature control, cross-contamination,
# handwashing, pest presence, sanitizing)
HIGH_RISK_VIOLATIONS = {1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 22, 27, 28, 31, 35, 41}
